spring:
  application:
    name: parking-lot-navigator
  profiles:
    default: local
  datasource:
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Seoul'
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
